language: node_js
node_js: '0.10'

script:
  - npm test

before_install:
  - npm install -g grunt-cli

deploy:
  provider: npm
  email: 'git_nikku@nixis.de'
  api_key:
    secure: Z68dnamLZto2I8BUWpuZoBOlmieAdsHY5PoyLhHNooZWnNFoU2FboZaplNQSmrr5Ve+tv8GUhotcWCKsnIw/mJiDeHFed+oDgca39i+8xGSpu3f+zELqzVfU+bEVZ4zDlAgfNGNGSHkOpX2Vyyzb7RqTX4vs2EOLnT4J4VM8zig=
  on:
    tags: true
